keycloak:
  ## @section Keycloak parameters

  ## Bitnami Keycloak image version
  ## ref: https://hub.docker.com/r/bitnami/keycloak/tags/
  ## @param image.registry [default: REGISTRY_NAME] Keycloak image registry
  ## @param image.repository [default: REPOSITORY_NAME/keycloak] Keycloak image repository
  ## @skip image.tag Keycloak image tag (immutable tags are recommended)
  ## @param image.digest Keycloak image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag
  ## @param image.pullPolicy Keycloak image pull policy
  ## @param image.pullSecrets Specify docker-registry secret names as an array
  ## @param image.debug Specify if debug logs should be enabled
  ##
  image:
    registry: registry.bare.pandrosion.org
    repository: edp/service/redqueen/iam-keycloak-image/keycloak
    tag: 25.0.6-2
    digest: ""
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: https://kubernetes.io/docs/concepts/containers/images/#pre-pulled-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## Example:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets:
      - gitlab-registry-credentials
  ## Keycloak authentication parameters
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/keycloak#admin-credentials
  ##
  auth:
    ## @param auth.adminUser Keycloak administrator user
    ##
    adminUser: admin
    ## @param auth.adminPassword Keycloak administrator password for the new user
    ##
    adminPassword: "admin"
    ## @param auth.existingSecret Existing secret containing Keycloak admin password
    ##
    existingSecret: "admin-password"
    ## @param auth.passwordSecretKey Key where the Keycloak admin password is being stored inside the existing secret.
    ##
    passwordSecretKey: "password"

  ## HTTPS settings
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/keycloak#tls-encryption
  ##
  tls:
    ## @param tls.enabled Enable TLS encryption. Required for HTTPs traffic.
    ##
    enabled: false
    ## @param tls.existingSecret Existing secret containing the TLS certificates per Keycloak replica
    ## Create this secret following the steps below:
    ## 1) Generate your truststore and keystore files (more info at https://www.keycloak.org/docs/latest/server_installation/#_setting_up_ssl)
    ## 2) Rename your truststore to `keycloak.truststore.jks` or use a different name overwriting the value 'tls.truststoreFilename'.
    ## 3) Rename your keystores to `keycloak.keystore.jks` or use a different name overwriting the value 'tls.keystoreFilename'.
    ## 4) Run the command below where SECRET_NAME is the name of the secret you want to create:
    ##       kubectl create secret generic SECRET_NAME --from-file=./keycloak.truststore.jks --from-file=./keycloak.keystore.jks
    ## NOTE: If usePem enabled, make sure the PEM key and cert are named 'tls.key' and 'tls.crt' respectively.
    ##
    ## @param tls.usePem Use PEM certificates as input instead of PKS12/JKS stores
    ## If "true", the Keycloak chart will look for the files keycloak.key and keycloak.crt inside the secret provided with 'existingSecret'.
    ##
    usePem: true
  ## @param production Run Keycloak in production mode. TLS configuration is required except when using proxy=edge.
  ##
  production: true
  ## @param proxy reverse Proxy mode edge, reencrypt, passthrough or none
  ## ref: https://www.keycloak.org/server/reverseproxy
  ##
  proxy: passthrough

  extraEnvVars:
    - name: KC_HEALTH_ENABLED
      value: "true"
      #- name: KC_VAULT
      #  value: "file"
      #- name: KC_VAULT_DIR
      #  value: "/etc/gke-secrets"
    - name: KC_LOG_LEVEL
      value: INFO,org.keycloak.events:DEBUG
    - name: QUARKUS_HTTP_LIMITS_MAX_HEADER_LIST_SIZE
      value: "20480"

  ## @param extraEnvVarsCM Name of existing ConfigMap containing extra env vars
  ##
  extraEnvVarsCM: ""
  ## @param extraEnvVarsSecret Name of existing Secret containing extra env vars
  ##
  extraEnvVarsSecret: ""

  ## @section Keycloak statefulset parameters

  ## @param replicaCount Number of Keycloak replicas to deploy
  ##
  replicaCount: 2

  ## @param topologySpreadConstraints Topology Spread Constraints for pod assignment spread across your cluster among failure-domains. Evaluated as a template
  ## Ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#spread-constraints-for-pods
  ##
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: node
      whenUnsatisfiable: ScheduleAnyway #ScheduleAnyway | DoNotSchedule
  service:
    ## @param service.type Kubernetes service type
    ##
    type: LoadBalancer
    ## @param service.http.enabled Enable http port on service
    ##
    http:
      enabled: false
    ## @param service.sessionAffinity Control where client requests go, to the same pod or round-robin
    ## Values: ClientIP or None
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/
    ##
    sessionAffinity: ClientIP
    ## @param service.loadBalancerIP loadBalancerIP for the SuiteCRM Service (optional, cloud specific)
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-loadbalancer
    ##
    loadBalancerIP: "34.159.48.164" # ip_address

  serviceAccount:
    ## @param serviceAccount.automountServiceAccountToken Auto-mount the service account token in the pod
    ##
    automountServiceAccountToken: true

  ## Keycloak Pod Disruption Budget configuration
  ## ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/
  ##
  pdb:
    ## @param pdb.create Enable/disable a Pod Disruption Budget creation
    ##
    create: false
    ## @param pdb.minAvailable Minimum number/percentage of pods that should remain scheduled
    ##
    minAvailable: 1

  ## Metrics configuration
  ##
  metrics:
    ## Prometheus Operator ServiceMonitor configuration
    ##
    serviceMonitor:
      endpoints:
        - path: /metrics
        - path: /realms/master/metrics

  ## @section Database parameters

  ## PostgreSQL chart configuration
  ## ref: https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
  ## @param postgresql.enabled Switch to enable or disable the PostgreSQL helm chart
  ## @param postgresql.auth.postgresPassword Password for the "postgres" admin user. Ignored if `auth.existingSecret` with key `postgres-password` is provided
  ## @param postgresql.auth.username Name for a custom user to create
  ## @param postgresql.auth.password Password for the custom user to create
  ## @param postgresql.auth.database Name for a custom database to create
  ## @param postgresql.auth.existingSecret Name of existing secret to use for PostgreSQL credentials
  ## @param postgresql.auth.secretKeys.userPasswordKey Name of key in existing secret to use for PostgreSQL credentials. Only used when `auth.existingSecret` is set.
  ## @param postgresql.architecture PostgreSQL architecture (`standalone` or `replication`)
  ##
  postgresql:
    primary:
      resourcesPreset: "small"
    enabled: true
    auth:
      postgresPassword: ""
      username: bn_keycloak
      password: ""
      database: bitnami_keycloak
      existingSecret: "database-password"
    architecture: replication
    backup:
      ## @param backup.enabled Enable the logical dump of the database "regularly"
      enabled: true
      cronjob:
        schedule: "0 5 * * *"
        #schedule: "1 * * * *"
        concurrencyPolicy: Forbid
        failedJobsHistoryLimit: 1
        successfulJobsHistoryLimit: 3
        restartPolicy: OnFailure
        podSecurityContext:
          enabled: true
          fsGroup: 1001
        containerSecurityContext:
          runAsUser: 0
          runAsGroup: 0
          runAsNonRoot: false
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
        ## @param backup.cronjob.command Set backup container's command to run
        command:
          - /bin/sh
          - -c
          #- "sleep 100000"
          - "pg_dumpall --clean --if-exists --load-via-partition-root --quote-all-identifiers --no-password --file=${PGDUMP_DIR}/pg_dumpall-$(date '+%Y-%m-%d-%H-%M').pgdump && ls -al /backup/pgdump"

        ## @param backup.cronjob.labels Set the cronjob labels
        labels: {}
        ## @param backup.cronjob.annotations Set the cronjob annotations
        annotations: {}
        storage:
          ## @param backup.cronjob.storage.existingClaim Provide an existing `PersistentVolumeClaim` (only when `architecture=standalone`)
          ## If defined, PVC must be created manually before volume will be bound
          ##
          #existingClaim: "keycloak-dev-poc-postgresql-pgdumpall-1"
          existingClaim: ""
          ## @param backup.cronjob.storage.resourcePolicy Setting it to "keep" to avoid removing PVCs during a helm delete operation. Leaving it empty will delete PVCs after the chart deleted
          ##
          resourcePolicy: "keep"
          accessModes:
            - ReadWriteOnce
          size: 8Gi
          annotations: {}
          mountPath: /backup/pgdump
